/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Ok': '好的',
    'Prestige': '声望',
    'PURCHASED.': '已购买。',
    'Shop': '商店',
    'Premium': '优质',
    'Skills': '技能',
    'Sort': '排序',
    'Category Bonuses': '类别奖励',
    'Clean': '清理',
    'Close': '关闭',
    'CURRENCY': '货币',
    'Community and contacts': '社区和联系方式',
    'Cook': '烹饪',
    'Current stats': '当前统计',
    'Progress': '进度',
    'progress': '进度',
    'Put': '放',
    'Unlocked skills': '已解锁技能',
    'up': '提升',
    'THANK YOU!': '感谢你!',
    'so it doesn\'t work properly in': '所以它在里面不能正常工作',
    'Take': '拿',
    'New batch': '新一批',
    'History': '历史',
    'from text ←': '来自文本 ←',
    'Info': '信息',
    'Incognito mode': '无痕模式',
    'If you have questions please contact the dev': '如有疑问，请联系开发人员',
    'Options': '选项',
    'PERMANENT': '永久',
    'Restaurant': '餐馆',
    'Restaurant menu': '餐馆菜单',
    'Restaurant name': '餐馆名称',
    'Select all text': '全选文本',
    'Sextuple Cook': '六重烹饪',
    ' Dark Mode': ' 深色模式',
    ' Engineering-exponential notation': '工程指数符号',
    'Double Cook': '双重烹饪',
    'and earned': '并获得',
    'Dishes': '碗碟',
    'Load': '加载',
    'All': '全部',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'For your first Prestige, it is good to get to about 10 Prestige Points, but if you': '对于您的第一次声望，最好获得大约10个声望点，但是如果您',
    'Exporting the game will load it and then  automatically prestige it to prevent exploits. Continue?': '导出游戏将加载它，然后自动声望它，以防止利用。继续吗?',
    'Every purchase supports the game and its solo dev.': '每次购买都支持该游戏及其单独开发。',
    'a third option too.': '还有第三种选择。',
    'Kitchen': '厨房',
    ' 1 Prestige Booster': '1声望助推器',
    '2 options to choose from, you\'ll get': '2种选择，您将获得',
    'You were away for': '你离开了',
    'You\'ll lose all your money and dishes and gain ': '您将失去所有的金钱和菜肴并获得收益',
    'Prestige Boosters': '声望助推器',
    'Loading error. The game requires JavaScript to be enabled. Here are the <a href=\"https://www.enable-javascript.com/\">\n instructions how to enable JavaScript in your web browser</a>': '载入错误。 游戏需要启用JavaScript。 这是<a href=\"https://www.enable-javascript.com/\"> \n说明，如何在网络浏览器中启用JavaScript </a>',
    'Welcome back!': '欢迎回来！',
    'want to start again, you can go earlier.': '要重新开始，可以早点去。',
    'Unlocks at': '解锁于',
    'Triple Cook': '三重烹饪',
    'Triple choice': '三重选择',
    'This is not the prestige system. You probably don\'t want to do this if you don\'t know what it means.': '这不是声望系统。 如果您不知道这意味着什么，那么您可能不想这样做。',
    'The game uses local storage to save progress,': '游戏使用本地存储来保存进度，',
    'Unlocks with Prestige Boosters skill': '使用声望助推器技能解锁',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "TIME: ": "时间: ",
    "Supercook": "超级厨师",
    "Cheap": "便宜",
    "Cooks total": "总计烹饪",
    "Dessert": "点心",
    "Fastfood": "快餐",
    "Drink": "饮料",
    'Meat': '肉',
    'Seafood': '海鲜',
    "Income": "收入",
    "Vegan": "素食",
    "Skip ": "跳过 ",
    "Tier ": "层 ",
    "Max Cook Qty:": "最高烹饪质量：",
    "Max Dish Level:": "最高菜肴等级：",
    "Min Cook Qty:": "最低烹饪质量：",
    "Mult:": "加成:",
    "New (": "新 (",
    "Premium: ": "优质：",
    "Active": "激活",
    "Dishwashing ": "洗盘子 ",
    "Email:": "邮箱:",
    "Buy": "购买",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    " sec": " 秒",
    " Gems": " 宝石",
    "Coupons": "优惠券",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    'Whenever you get': '每当你得到',
    'on the right →': '在右边→',
    'When you Prestige, you restart the game to get Prestige Points and Skill Points.': '当您获得声望时，您可以重新启动游戏以获得声望点和技能点。',
    'You can spend gems on ingame purchases': '您可以在游戏中购买宝石',
    'Prestige Points increase your total income by 10% each.': '声望点可将您的总收入提高10％。',
    "(Hover over skills and rainbow bar at the main screen to see more descriptions.": "（将鼠标悬停在主屏幕上的技能和彩虹条上可查看更多说明。",
    'Skill Points are used to buy skills below.': '技能点数用于购买以下技能。',
    'Hard Reset (right click or long hold': '硬重置（右键单击或长按',
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+) 秒$/,
    /^(\d+)\:(\d+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(.+)\(prestiges the game$/, '（对游戏进行声望'],
    [/^(.+)On prestige you\'ll get:(.+)$/, '进行声望，您将获得：'],
    [/^(.+)Available Skill Points:(.+)$/, '可用技能点：'],
    [/^(.+)Total Prestige Points:(.+)$/, '总声望点：'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);